Update
floydhub/floyd-docs pull request #170
Opened 2018-09-18 17:06 UTC by ReDeiPirati

- Update `floyd run` command
- Important: Training metrics are only available for Command Job
- Set TF 1.8 as default
- Fix typo

2018-09-18 18:27 UTC, narenst approved these changes

2018-09-20 17:30 UTC, whatrocks requested changes
Why did you add back `jupyter` as a mode. I've removed that from the docs. Can you fix that in the run section?

2018-09-20 19:04 UTC, ReDeiPirati commented
@whatrocks I didn't notice :facepalm:, I'll fix it now.

2018-09-21 20:19 UTC, whatrocks approved these changes
:shipit:

2018-09-21 20:21 UTC, narenst approved these changes

2018-09-21 22:58 UTC, merged