Update
floydhub/floyd-docs pull request #180
Opened 2018-11-07 15:14 UTC by ReDeiPirati

Add Encoding issue for In-app alerts and warn users about serving supported envs

2018-11-07 19:43 UTC, whatrocks commented on docs/commands/run.md
> +    _This is a common issue between **Windows users**_: it could happens that your Terminal is using a different encoding from the one expected from the remote machine. Here are some examples:
_This is a common issue for **Windows users**_: This occurs when your Windows terminal is using a different encoding from the one expected by the remote machine. Here are some examples:

2018-11-07 19:44 UTC, whatrocks commented on docs/commands/run.md
> +    Unfortunately, there isn't a silver bullet, but you can use the `Command` view of the Job's Overview page to help at debugging it. More in general, if you will notice this issue, you can try to s
Unfortunately, there isn't a silver bullet to identifying this issue, but you can use the `Command` view of the Job's Overview page to help debug and identify this issue. More generally, if you notice this issue, you can try to switch single quotes with double or vice versa, and remove the slash if you are indenting the commands on multiple lines - these changes usually fix the issue in 99% of the cases. If not, please reach out to us at support@floydhub.com.

2018-11-07 19:44 UTC, whatrocks commented on docs/faqs/using_floydhub.md
> +### Encoding issue
same changes as above

2018-11-07 19:45 UTC, whatrocks commented on docs/faqs/using_floydhub.md
> + Unfortunately, there isn't a silver bullet, but you can use the `Command` view of the Job's Overview page to help at debugging it. More in general, if you will notice this issue, you can try to swit
same as above

2018-11-07 19:45 UTC, whatrocks commented on docs/guides/serving.md
> +    The uswgi application server will spawn 2 workers (processes) for serving your application. This can be a source of [race conditions](https://en.wikipedia.org/wiki/Race_condition#software)! Writi
but if your use-case requires it

2018-11-07 19:45 UTC, whatrocks commented on docs/guides/serving.md
> +    - TensoFlow (`--env tensorlfow-1.5` and later)
TensorFlow

2018-11-07 19:45 UTC, whatrocks commented on docs/guides/serving.md
> +    - TensoFlow (`--env tensorlfow-1.5` and later)
tensorflow-1.5`

2018-11-07 19:46 UTC, whatrocks requested changes
Looks good - just a few spelling updates.

2018-11-07 20:02 UTC, ReDeiPirati commented
Thanks @whatrocks!

2018-11-12 18:56 UTC, ReDeiPirati commented
@narenst @houqp quick review, please?

2018-11-12 20:12 UTC, whatrocks approved these changes

2018-11-12 20:49 UTC, merged